services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: "pip install -r render_requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
